#!/bin/bash

./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh
./extractNext.sh

